# Generated by Django 4.2.2 on 2023-06-14 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Galaxia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Planeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Plumbus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('f_creacion', models.DateField()),
                ('f_caducidad', models.DateField()),
                ('c_chumbles', models.CharField(choices=[('KC°', 'KC°'), ('%Z', '%Z'), ('O', 'O'), ('O)', 'O)')], max_length=10)),
                ('imagen', models.ImageField(upload_to='static/app/imgs')),
            ],
        ),
        migrations.CreateModel(
            name='PlumbusX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('largo_dingle_dop', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vibracion_floops', models.IntegerField()),
                ('grodus_inalambrico', models.BooleanField()),
                ('imagen', models.ImageField(upload_to='static/app/imgs')),
            ],
        ),
        migrations.CreateModel(
            name='Universo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado'), ('DEVUELTO', 'Devuelto')], default='Pendiente', max_length=15)),
                ('direccion_envio', models.CharField(max_length=150)),
                ('carrito', models.ManyToManyField(to='app.carrito')),
            ],
        ),
        migrations.CreateModel(
            name='FormularioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_titular', models.CharField(max_length=100)),
                ('numero_tarjeta', models.CharField(max_length=16)),
                ('fecha_expiracion', models.DateField()),
                ('codigo_seguridad', models.CharField(max_length=4)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('direccion_envio', models.CharField(max_length=150)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('galaxia_envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.galaxia')),
                ('planeta_envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.planeta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='plumbus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.plumbus'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='plumbusX',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.plumbusx'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
