# Generated by Django 4.2.2 on 2023-06-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plumbus',
            name='imagen',
            field=models.ImageField(upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='plumbusx',
            name='imagen',
            field=models.ImageField(upload_to='productos'),
        ),
    ]
