# Generated by Django 4.2.2 on 2023-06-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_plumbus_imagen_alter_plumbusx_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plumbus',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
