# Generated by Django 4.2.2 on 2023-06-15 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_plumbus_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariopago',
            name='universo_envio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.universo'),
        ),
    ]
