# Generated by Django 4.1.7 on 2023-07-07 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_itemcarrito_producto'),
        ('app', '0007_contacto_asunto_alter_contacto_num_telefono'),
    ]

    operations = [
    ]
